name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login to docker registry
      run: docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password ${{ secrets.DOCKERHUB_TOKEN }}
    - uses: 'finnp/create-file-action@master'
    - name: Build Docker file
      env:
        FILE_NAME: '.env'
        FILE_BASE64: '${{ secrets.PRODUCTION_ENV }}'
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag betpoa-backend:$(date +%s)
    - name: Tag docker image
      run: docker tag betpoa-backend ${{ secrets.DOCKERHUB_USERNAME }}/betpoa-backend || true
    - name: Push image to docker hub
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/betpoa-backend
    
